<?php

return [
    'mode'                     => 'utf-8',
    'format'                   => 'A4',
    'default_font_size'        => '10',
    'default_font'             => 'vazir',
    'margin_left'              => 3,
    'margin_right'             => 3,
    'margin_top'               => 5,
    'margin_bottom'            => 5,
    'margin_header'            => 0,
    'margin_footer'            => 0,
    'orientation'              => 'P',
    'title'                    => 'Report',
    'subject'                  => '',
    'author'                   => '',
    'watermark'                => '',
    'show_watermark'           => false,
    'show_watermark_image'     => false,
    'watermark_font'           => 'sans-serif',
    'display_mode'             => 'fullpage',
    'watermark_text_alpha'     => 0.1,
    'watermark_image_path'     => '',
    'watermark_image_alpha'    => 0.2,
    'watermark_image_size'     => 'D',
    'watermark_image_position' => 'P',
    'custom_font_dir'          => base_path('/public/assets/fonts/farsi-fonts'),
    'custom_font_data'         => [
        'vazir' => [
            'R'  => 'vazir-500.ttf',
            'useOTL' => 0xFF,
            'useKashida' => 75,
        ],
        'nazanin' => [
            'R'  => 'nazanin.ttf',
            'useOTL' => 0xFF,
            'useKashida' => 75,
        ],
    ],
    'auto_language_detection'  => false,
    'temp_dir'                 => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),
    'pdfa'                     => false,
    'pdfaauto'                 => false,
    'use_active_forms'         => false,
];
